version: '3.3'

services:

  infocoin:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "3000:3000"

  cron:
    container_name: cron
    image: cron
    build:
      context: .
      dockerfile: ./Dockerfile.cron