version: '3.8'

services:

  infocoin:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"

  cron:
    container_name: cron
    image: cron
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.cron