version: '3.8'
services:
  infocoin:
    command: dev
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
        - /usr/src/app/.next
  cron:
    container_name: cron
    image: cron
    build:
      context: .
      dockerfile: ./Dockerfile.cron