import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link'
import { useEffect, useState } from 'react';
import { Loader } from '../components'
// import styles from '../styles/Home.module.css'

export default function Home() {
  const [userCoins, setUserCoins] = useState([]);
  const [userCoinsIsLoading, setUserCoinsIsLoading] = useState(true);

  useEffect(() => {
    fetch('/api/accessible-coins')
      .then(response => response.json())
      .then((data) => setUserCoins(data))
      .finally(() => {
        setUserCoinsIsLoading(false);
      })
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen">
        <div className="flex items-baseline justify-between py-6">
          <h1 className="text-5xl font-extrabold tracking-tight text-gray-900">Infocoin</h1>
        </div>
        {
          userCoinsIsLoading ? (
            <div className="flex h-50 items-center justify-center w-full h-full grow">
              <Loader />
            </div>
          ) : userCoins.map((userCoin) => {
            return (
              <div key={userCoin.coin} className='flex mb-6 bg-white rounded-md duration-300 hover:shadow-md shadow-sm border sm:px-3 lg:px-4 sm:py-3 lg:py-4 items-center'>
                <span className="flex h-3 w-3 relative sm:mr-3 lg:mr-4">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-green-500"></span>
                </span>
                <div>
                  <h2 className='text-2xl font-extrabold'>{userCoin.coin}</h2>
                  <span className='text-sm text-slate-400'>{userCoin.name}</span>
                </div>
                <span className='text-3xl font-extrabold flex-auto text-right sm:mr-3 lg:mr-4'>
                  {userCoin.free}
                </span>
                <Link href={`/${userCoin.coin}`}>
                  <a href="#" className="text-xs border-2 hover:border-blue-600 hover:text-blue-600 border-blue-500 text-blue-500 font-bold px-2 py-2 rounded-md">
                    Trade
                  </a>
                </Link>
              </div>
            )
          })
        }
      </main>
    {/* <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div> */}
    </>
  )
}
