import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import {
  FullBlockLoader,
  Button,
  ModalWindow,
  ModalWindowBodyAddCoin,
  FullBlockMessage,
} from '../components';

export default function Home() {
  const [userCoins, setUserCoins] = useState([]);
  const [userCoinsIsLoading, setUserCoinsIsLoading] = useState(false);
  const [addCoinIsOpenModalWindow, setAddCoinIsOpenModalWindow] =
    useState(false);

  const getAccessibleCoins = () => {
    setUserCoinsIsLoading(true);

    fetch('/api/accessible-coins')
      .then((response) => response.json())
      .then((data) => setUserCoins(data))
      .finally(() => {
        setUserCoinsIsLoading(false);
      });
  }

  useEffect(() => {
    getAccessibleCoins();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 min-h-screen'>
        <div className='flex flex-row items-center justify-between py-6'>
          <div>
            <h1 className='text-5xl font-extrabold tracking-tight text-gray-900'>
              Infocoin
            </h1>
          </div>
          <div>
            <Button
              intent='primary'
              onClick={() => setAddCoinIsOpenModalWindow(true)}
            >
              Add new coin
            </Button>
          </div>
        </div>

        {userCoinsIsLoading ? <FullBlockLoader /> : null}

        {!userCoinsIsLoading && userCoins.length === 0 ? (
          <FullBlockMessage text='No data found' />
        ) : null}

        {!userCoinsIsLoading && userCoins.length !== 0 ? (
          <div className='grid grid-cols-4 gap-8'>
            {userCoins.map((userCoin) => {
              return (
                <div
                  key={userCoin.coin}
                  className='py-4 px-4 text-center bg-white rounded-md duration-300 hover:shadow-md shadow-sm border relative'
                >
                  <p className='text-xl font-extrabold'>{userCoin.coin}</p>
                  <p className='text-xs  text-slate-400'>
                    {userCoin.fullCoinName}
                  </p>
                  <p className='text-1xl font-extrabold mb-4 mt-4'>
                    {userCoin.amount}
                  </p>
                  <span className='flex h-3 w-3 absolute sm:right-3 lg:right-4 sm:top-3 lg:top-4'>
                    <span className='animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75'></span>
                    <span className='relative inline-flex rounded-full h-3 w-3 bg-green-500'></span>
                  </span>
                  <Link href={`/${userCoin.id}`}>
                    <a className='text-xs border-2 hover:border-blue-600 hover:text-blue-600 border-blue-500 text-blue-500 font-bold px-2 py-2 inline-block rounded-md'>
                      Trade
                    </a>
                  </Link>
                </div>
              );
            })}
          </div>
        ) : null}
      </main>
      <ModalWindow isOpen={addCoinIsOpenModalWindow} msgTitle='Add new coin'>
        <ModalWindowBodyAddCoin
          msgBtnApply='Add coin'
          msgBtnClose='Close'
          onApply={() => getAccessibleCoins()}
          onClose={() => setAddCoinIsOpenModalWindow(false)}
        />
      </ModalWindow>
    </>
  );
}
